### ISSUE TITLE
Cutting off last characters sending SMS

### ISSUE THREAD

**Issue by leoncc** [emilsedgh/modem#4]
When using the modem.sms function I am experiencing that the last few characters are cut of when viewing the sms message on the receiving phone.

function sendSMS() {
    console.log('Attempting to send SMS');
    modem.sms({
        receiver: '0761234567',
        text: 'Test text from app.js on Mac.',
        encoding: '7bit'
    }, function (err, sent_ids) {
        console.log('>>', arguments);
        if (err)
            console.log('Error sending sms:', err);
        else
            console.log('Message sent successfully, here are reference ids:', sent_ids.join(','));
    });
}

For instance: Test text from app.js on Mac. gets cut off toTest text from app.js on M

Have you experienced this?

Thanks
Leon

**Comment by engkan2kit** [comment]
I am experiencing this too.

**Comment by leoncc** [comment]
Hi,

In the scenario I wanted to use SMSs I discovered I needed a bit more. I want to be able to send SMSs in a queued manner (if things get busy), process delivery reports, receive SMS etc. I downloaded the Gammu SMSD deamon from wammu.eu. Unfortunately you need to compile it with cmake, but I found that relatively easy. It works for me, but maybe your scenario is different. 

Regards
Leon

**Comment by engkan2kit** [comment]
My scenario is this:
I have multiple GSM modems. I have a main nodejs app that stores the sms message and destination in mongodb. Each GSM modem has node.js app(same script but different device addresses) that is connected to the main app and fetches queued messages in the mongoDB. Also, whenever the main app stores the mongodb, it notifies all gsm node that there is a new data to be fetch( to avoid polling the database). Right now I am using only one GSM modem. I have experience this problem(cutting of lasst few characters as well as corrupted multiple messages when more that 160 characters are sent.). I suspect the problem is with the PDU so I am thinking of not using the PDU and directly use the Text mode of GSM modems since mine supports it.

**Comment by leoncc** [comment]
Most important I think is that only one application should communicate with one modem as while you are busy sending other messages might come in, for instance delivery reports if you request them. I have one deamon running per modem, which handles the sending and receiving. In my case I also need to process incoming SMSs.
